# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:22
from __future__ import unicode_literals

import apps.core.models
from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=apps.core.models.Images.image_path)),
                ('image_thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, upload_to=apps.core.models.Images.image_thumb_path)),
            ],
            options={
                'verbose_name_plural': 'Fotos',
                'verbose_name': 'Foto',
            },
        ),
    ]
