# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_images_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('galery', models.ManyToManyField(to='core.Images')),
            ],
            options={
                'verbose_name_plural': 'Coleções',
                'verbose_name': 'Coleção',
            },
        ),
    ]
