# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 16:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_colecoes_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElasUsam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('galery', models.ManyToManyField(to='core.Images')),
            ],
            options={
                'verbose_name_plural': 'Elas Usam',
                'verbose_name': 'Elas Usam',
            },
        ),
    ]
