# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:24
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_elasusam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('ddd', models.IntegerField(validators=[django.core.validators.MinValueValidator(10, message='Certifique-se que este valor possui 2 digitos.'), django.core.validators.MaxValueValidator(99)], verbose_name='DDD')),
                ('phone', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Telefone')),
                ('message', models.TextField()),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Email',
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('galery', models.ManyToManyField(to='core.Images')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
