# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_email_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='send_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
