# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171123_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
