# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_images_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecoes',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elasusam',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
