# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 11:59
from __future__ import unicode_literals

import apps.core.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180105_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=apps.core.models.Images.image_thumb_path),
        ),
    ]
