# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 15:10
from __future__ import unicode_literals

import apps.core.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180227_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to=apps.core.models.Images.image_thumb_path),
            preserve_default=False,
        ),
    ]
